[build.environment]
  HUGO_VERSION = "0.69.0"

[build]
  command = """\
            sed -i s#TT_PLACEHOLDER_REPOSITORY#${REPOSITORY_URL}#g site/config/_default/config.yaml \
            && sed -i s#TT_PLACEHOLDER_BRANCH#${BRANCH}#g site/config/_default/config.yaml \
            && sed -i s#TT_PLACEHOLDER_URL#${URL}#g site/config/_default/config.yaml \
            && yarn build"""

  publish = "dist"

[template.environment]
  HUGO_TITLE = "Title of your Zettenkasten"
  HUGO_PARAMS_AUTHOR = "Your name"
  HUGO_PARAMS_CONTACT_PHONE = "e.g. +49 123 45678"
  HUGO_PARAMS_CONTACT_EMAIL = "e.g. first@last.name"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/notes/:id/:title"
  to = "/notes/:id"
  status = 200
  force = false

[[redirects]]
  from = "/references/:id/:title"
  to = "/references/:id"
  status = 200
  force = false