[build.environment]
  HUGO_VERSION = "0.69.0"

[build]
  command = """\
            sed -i "s|TT_PLACEHOLDER_REPOSITORY|${REPOSITORY_URL}|g
            s|TT_PLACEHOLDER_BRANCH|${BRANCH}|g
            s|TT_PLACEHOLDER_URL|${URL}|g
            s|TT_PLACEHOLDER_AUTHOR|${TT_AUTHOR}|g
            s|TT_PLACEHOLDER_PHONE|${TT_PHONE}|g
            s|TT_PLACEHOLDER_EMAIL|${TT_EMAIL}|g
            " site/config/_default/config.yaml \
            && yarn build"""

  publish = "dist"

[template.environment]
  HUGO_TITLE = "Title of your Zettenkasten"
  TT_AUTHOR = "Your name"
  TT_PHONE = "Phone e.g. +49 123 45678"
  TT_EMAIL = "Mail e.g. first@last.name"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/notes/:id/:title"
  to = "/notes/:id"
  status = 200
  force = false

[[redirects]]
  from = "/references/:id/:title"
  to = "/references/:id"
  status = 200
  force = false