baseURL: "TT_PLACEHOLDER_URL"
languageCode: "en-en"
title: "TT_PLACEHOLDER_SITE_TITLE"

params:
  author: "TT_PLACEHOLDER_AUTHOR"
  about:
    address: "TT_PLACEHOLDER_ADDRESS"
    contact:
      phone: "TT_PLACEHOLDER_PHONE"
      email: "TT_PLACEHOLDER_EMAIL"
  backend:
    name: github
    repo: "TT_PLACEHOLDER_REPOSITORY"
    branch: "TT_PLACEHOLDER_BRANCH"

enableGitInfo: true

taxonomies:
  topic: topics
  tag: tags
  flow: flows
  keyword: keywords
  
Paginate: 10

related:
  threshold: 70
  includeNewer: true
  toLower: true
  indices:
  - name: keywords
    weight: 20
  - name: topics
    weight: 30    
  - name: date
    pattern: 20060102
    weight: 10
      
